# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.

theme = "blowfish"
baseURL = "https://joelmarks.online/"
defaultContentLanguage = "en"

enableRobotsTXT = true
pagerSize = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "G-Y5KL76FM6Q"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
