languageCode = "en"
languageName = "English"
weight = 1
title = "Joel Marks"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo-white.png"
secondaryLogo = "logo-black.png"
description = "Joel Marks consulting coach"
copyright = "(c)2025 JoelMarks"

[author]
name = "Joel Marks"
image = "img/joelmarks_avatar.jpg"
headline = "Consulting coach"
bio = "Solution focused practitioner"
links = [ { linkedin = "https://linkedin.com/in/joel-marks"}, { goodreads = "https://www.goodreads.com/joelmarks" } ]
