languageCode = "en"
languageName = "English"
weight = 1
title = "Joel Marks"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo-white.png"
secondaryLogo = "logo-black.png"
description = "A personal homepage"
copyright = "Copy, _right?_ :thinking_face:"

[author]
name = "Joel Marks"
image = "img/joelmarks_avatar.jpg"
headline = "Solution Focused Practitioner"
bio = "Solution focused practitioner, trained with BRIEF"
links = [ { link = "https://joelmarks.online/" }, { linkedin = "https://linkedin.com/in/joel-marks"}, { goodreads = "https://www.goodreads.com/joelmarks" } ]
